[build]
  publish = "." 
  functions = "netlify/functions"

# Handle preflight OPTIONS requests for all functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat" # Pass through, but headers below will apply
  status = 200 # Must be 200 for OPTIONS preflight
  force = true # Ensure this rule is applied
  # Headers for the OPTIONS preflight response
  [redirects.headers]
    Access-Control-Allow-Origin = "*" # Or "https://www.peekmyip.com"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" # Add any other headers your client might send

# Handle actual function calls (GET, POST etc.)
[[redirects]]
  from = "/api/*" # If your JS calls /api/ paths
  to = "/.netlify/functions/:splat"
  status = 200 # Rewrite to function
  force = true
  # Headers for the actual GET/POST response from the function
  [redirects.headers]
    Access-Control-Allow-Origin = "*" # Or "https://www.peekmyip.com"
    # Content-Type will be set by your function

# This rule ensures that if someone requests /script.js,
# Netlify serves the file from /public/script.js.
[[redirects]]
  from = "/script.js"
  to = "/public/script.js"
  status = 200 
