[build]
  publish = "." 
  functions = "netlify/functions"

# Global headers for all function responses
[[headers]]
  for = "/.netlify/functions/*" # Applies to all your functions
  [headers.values]
    Access-Control-Allow-Origin = "*" # Or "https://www.peekmyip.com"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Redirects/Rewrites (from previous successful setup for static files)
[[redirects]]
  from = "/script.js"
  to = "/public/script.js" # Assuming you still have a public/script.js in dnsleak-tester for a direct Netlify site version
  status = 200 

[[redirects]]
  from = "/api/*" # If your blogspot script calls /api/ path
  to = "/.netlify/functions/:splat"
  status = 200
