[build]
  publish = "." # Serves index.html from root, and public/* from /
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" 
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]] # If your script.js directly calls /api/*
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
# No specific redirect needed for script.js if publish = "." handles public/ correctly
