[build]
  # This tells Netlify that the root of your repo is the publish directory.
  # Netlify will then automatically serve files from a "public" folder 
  # (if it exists at this root) as if they are at the root URL path.
  publish = "." 
  functions = "netlify/functions" # Specifies your functions directory

# This rule ensures that if someone requests /script.js,
# Netlify serves the file from /public/script.js.
# The status = 200 makes it a rewrite (serves the content without changing URL).
[[redirects]]
  from = "/script.js"
  to = "/public/script.js"
  status = 200 

# This rule ensures API calls are routed to your Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat" # :splat captures the wildcard part
  status = 200
