[build]
  publish = "." 
  functions = "netlify/functions"

# Redirect /api/* calls to Netlify functions
# AND apply CORS headers to these /api/* paths
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 # This makes it a rewrite (function invocation)
  force = true 
  # Headers for both OPTIONS preflight and actual GET/POST responses via /api/
  [redirects.headers]
    Access-Control-Allow-Origin = "*" 
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" 

# Fallback for any OPTIONS request to the actual function path,
# though the /api/* rule should catch most.
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
